{{if eq .Values.workload.type "cronjob"}}

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $fullname := include "vsync.fullname" . -}}
{{- $release_name := .Release.Name }}
{{- $vault := .Values.vault }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "vsync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vsync.name" . }}
    helm.sh/chart: {{ include "vsync.chart" . }}
    app.kubernetes.io/instance: {{ $release_name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "vsync.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
          - name: {{ $job.name }}
            image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            imagePullPolicy: {{ $job.image.imagePullPolicy }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 13 }}
            {{- end }}
            env:
            - name: VAULT_ADDR
              value: {{ $vault.source.address }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-vault-tokens
                  key: vault-token
            - name: DESTINATION_VAULT_ADDR
              value: {{ $vault.destination.address }}
            - name: DESTINATION_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-vault-tokens
                  key: destination-vault-token
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 15 }}
            {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}
{{end}}
