{{if eq .Values.workload.type "cronjob"}}

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $fullname := include "vsync.fullname" . -}}
{{- $release_name := .Release.Name }}
{{- $vault := .Values.vault }}

{{- range .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "vsync.name" . }}
    helm.sh/chart: {{ include "vsync.chart" . }}
    app.kubernetes.io/instance: {{ $release_name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: {{ .concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "vsync.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
          - name: vsync
            image: "{{ .image.repository }}:{{ .image.tag }}"
            imagePullPolicy: {{ .image.imagePullPolicy }}
            {{- if .command }}
            command: {{ .command }}
            {{- end }}
            {{- with .args }}
            args:
{{ toYaml . | indent 13 }}
            {{- end }}
            env:
            - name: VAULT_ADDR
              value: {{ $vault.source.address }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-vault-tokens
                  key: vault-token
            - name: DESTINATION_VAULT_ADDR
              value: {{ $vault.destination.address }}
            - name: DESTINATION_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-vault-tokens
                  key: destination-vault-token
            {{- with .resources }}
            resources:
{{ toYaml . | indent 15 }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
{{- end }}
{{end}}
