apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsync.fullname" . }}-vault-tokens
  labels:
    app: {{ template "vsync.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  vault-token: {{ .Values.vault.source.token | b64enc | quote }}
  destination-vault-token: {{ .Values.vault.destination.token | b64enc | quote }}
